main_website/urls.py
from django.urls import path
from . import views


app_name = 'main_website'

urlpatterns = [
    path('homepage/<str:company_name>/<str:stall_text>/', views.home_page, name='main_page'),
    path('lobby/<str:company_name>/<str:stall_text>/', views.lobby_page, name='lobby'),    
    path('auditorium/<str:company_name>/<str:stall_text>/', views.auditorium, name='auditorium'),     
    path('info_desk/<str:company_name>/<str:stall_text>/', views.info_desk, name='info_desk'),    
    path('exhibit_hall/<str:company_name>/<str:stall_text>/', views.exhibit_hall, name='exhibit_hall'),    
    path('resource_center/<str:company_name>/<str:stall_text>/', views.resource_center, name='resource_center'),    
    path('social_lounge/<str:company_name>/<str:stall_text>/', views.social_lounge, name='social_lounge'),                       
    path('zoom_start/', views.zoom_start, name='zoom_start'),    
    path('stall/<str:company_name>/<str:stall_text>/',views.stall,name='stalls'),                       
    path('stall_iframe',views.stall_iframe,name='stall_iframe'),
    path('stall_portal/<str:company_name>/<str:stall_text>/',views.stall_portal,name='stall_portal'),
    path('stall_details/<str:company_name>/<str:stall_text>/',views.stall_details,name='stall_details'),
    path('auditorium_owner/<str:company_name>/',views.auditorium_owner,name='auditorium_owner'),        
    path('stall_owner_page/<str:company_name>/',views.stall_owner_page,name='stall_owner_page'),
    path('stall_owner_chat/<str:company_name>/<str:stall_text>/',views.stall_owner_chat,name='stall_owner_chat'),    
    path('question',views.question,name = 'question'),
    path('photobooth/',views.photobooth,name='photobooth'),
    path('stall_analytics/<str:company_name>/<str:stall_text>/',views.stall_analytics,name='stall_analytics'),
    path('stall_add_documents/<str:company_name>/<str:stall_text>/',views.stall_add_documents,name='stall_add_documents'),
    path('stall_add_sales_representative/<str:company_name>/<str:stall_text>/',views.stall_add_sales_representatives,name='stall_add_sales_representatives'),


    path('first_floor/<str:company_name>/<str:stall_text>/',views.first_floor,name="first_floor"),
    path('first_floor/room1/<str:company_name>/<str:stall_text>/',views.first_floor_link1,name="first_floor_link1"),
    path('first_floor/room2/<str:company_name>/<str:stall_text>/',views.first_floor_link2,name="first_floor_link2"),
    path('first_floor/room3/<str:company_name>/<str:stall_text>/',views.first_floor_link3,name="first_floor_link3"),


    path('submit_polling_results/<str:company_name>/<str:stall_text>/',views.submit_polling_results,name="submit_polling_results"),
    path('update_doc/<str:company_name>/<str:stall_text>/',views.update_document,name="update_document"),
    path('update_social_media_link/<str:company_name>/<str:stall_text>/',views.update_social_media_link,name="update_social_media_link"),
    path('new_doc/<str:company_name>/<str:stall_text>/',views.new_document,name="new_document"),
    path('new_representative/<str:company_name>/<str:stall_text>/',views.new_representative,name="new_representative"),
    path('update_representative/<str:company_name>/<str:stall_text>/',views.update_representative,name="update_representative"),
    path('schedule_call/<str:company_name>/<str:stall_text>/',views.schedule_call_by_user,name="schedule_call"),

    path('feedback',views.FeeBack.as_view(),name='feedback')
]

users/urls.py
from django.urls import path,reverse_lazy
from django.contrib.auth import views as auth_views
from . import views

app_name = 'users'

urlpatterns = [
	path('',views.basic_login_redirect,name='basic_login'),
    path('register/<str:company_name>/<str:stall_text>/',views.register,name = 'register'),
    path('login/<str:company_name>/<str:stall_text>/', views.CustomLoginView.as_view(), name='login'),
    path('logout/<str:company_name>/<str:stall_text>/', views.CustomLogoutView.as_view(), name='logout'),
]

webinarwall/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('dashboard/', include('dashboard.urls')),    
    path('arena/', include('main_website.urls')),       
    # path('main_website/',include()) 
] #+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_website/forms.py
from django import forms
from users.models import MyUser
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import gettext, gettext_lazy as _
from django.contrib.auth import authenticate
from dashboard.models import OrganizerDetails
from main_website.models import FeedBack
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, ButtonHolder, Submit, Field
from crispy_forms.layout import Layout, Submit, Row, Column


class FeedbackForm(forms.ModelForm):

    class Meta:
        model = FeedBack
        fields = '__all__'
        labels = {
            "question1": "Please rate your overall satisfaction with the virtual conference",
            "question2": "Please rate your overall satisfaction with the exhibits area",
            "question3": "Please rate your overall satisfaction with the format of the conference",
            "question4": "Please rate your overall satisfaction with the access and convenience with the Platform use",
            "question5": "Please rate your overall satisfaction with the access and convenience with the Platform used ",
            "question6": "Please rate Quality of Audio & Visuals ",
            "question7": "The Quality of our sponsors / partners for the summit",
            "question8": "Have your organization embarking on any strategic initiatives approved to improve on Technology / IOT etc.?",
            "question9": "The likely time period of undertaking these strategic initiatives is",
            "question10": "Please provide any comments you have on future conference  platforms,  topics, speakers or general suggestions regarding the conference",
        }

    def __init__(self, *args, **kwargs):
        super(FeedbackForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
                Row('question1'),
                Row('question2'),
                'question3',
                'question4',
                'question5',
                'question6',
                'question7',
                'question8',
                'question9',
                'question10',
            ButtonHolder(
                Submit('submit', 'Submit', css_class='button white')
            )
        )

main_website/views.py
from django.shortcuts import render
from dashboard.models import OrganizerDetails, EventStallUsers, Stalls, StallZoom, Stall_Owner_documents,Stall_Sales_Representatives
from users.decorators import user_authorized_for_page
from django.urls import reverse_lazy
import hashlib
import hmac
import base64
import time
from django.contrib import messages
from django.http import JsonResponse, HttpResponse, HttpResponseRedirect
from users.models import MyUser
from .models import Notification, Analytics, Permanent_Poll_Answers
import urllib.parse
# from django.http import JsonResponse
from .models import Question, poll, another_poll_answers
import pdb
from .models import Message
from users.models import MyUser
from django.db.models import Q
from django.urls import reverse
from django.http import HttpResponseRedirect
from main_website.forms import FeedbackForm
from django.views.generic import CreateView
# Create your views here.

def calculate_registered_users(organizer):
    # organizer = OrganizerDetails.objects.get(name = company_name)
    return EventStallUsers.objects.filter(organizer_name=organizer).count()


def hall_array(organizer_details):
    return [organizer_details.hall_title_1, organizer_details.hall_title_2, organizer_details.hall_title_3,
            organizer_details.hall_title_4]


def question(request):
    question = request.GET.get('question', None)
    Question.objects.create(question=question, user=MyUser.objects.get(id=request.user.id).name)
    return JsonResponse({'success': 'success'})


#@user_authorized_for_page
def home_page(requests, company_name, stall_text):
    organizer_details = OrganizerDetails.objects.get(name=company_name)
    background_type = organizer_details.main_page_background_type
    background_url = organizer_details.main_page_background_url
    lobby_page_url = '127.0.0.1:8000/lobby/' + company_name + stall_text

    event_stall_users = EventStallUsers.objects.filter(organizer_name=organizer_details)
    user_ids = [i.event_user_id for i in event_stall_users]

    users = MyUser.objects.filter(id__in=user_ids).order_by('name')

    resource_links = [[organizer_details.resource_1_name, organizer_details.resource_1_link],
                      [organizer_details.resource_2_name, organizer_details.resource_2_link],
                      [organizer_details.resource_3_name, organizer_details.resource_3_link],
                      [organizer_details.resource_4_name, organizer_details.resource_4_link]]

    slides = [organizer_details.main_page_ppt_image1, organizer_details.main_page_ppt_image2,
              organizer_details.main_page_ppt_image3, organizer_details.main_page_ppt_image4]
    notifications_array,users_array = get_chats(requests,organizer_details)
    users_chat = zip(notifications_array, users_array)

    context = {
        'background_type': background_type,
        'banner_links': resource_links,
        'background_url': background_url,
        'lobby_page_url': lobby_page_url,
        'company_name': company_name,
        'stall_text': stall_text,
        'registered_users': calculate_registered_users(organizer_details),
        'main_page_front_banner_image': organizer_details.main_page_front_banner_image,
        
        'main_page_back_banner_image1': organizer_details.main_page_back_banner_image1,
        'main_page_back_banner_image2': organizer_details.main_page_back_banner_image2,
        'main_page_back_banner_image3': organizer_details.main_page_back_banner_image3,
        'main_page_back_banner_image4': organizer_details.main_page_back_banner_image4,
        
        'slides': slides,
        'hall_array': hall_array(organizer_details),
        'users':users,
        'users_chat':users_chat,
        'current_user': MyUser.objects.get(id=requests.user.id),        
    }

    # return render(requests, 'main_website/main_page.html', context)
    return render(requests, 'new/main_page.html', context)


# @user_authorized_for_page
def lobby_page(requests, company_name, stall_text):
    organizer_details = OrganizerDetails.objects.get(name=company_name)
    hall_titles = [organizer_details.hall_title_1, organizer_details.hall_title_2, organizer_details.hall_title_3,
                   organizer_details.hall_title_4]
    resource_links = [[organizer_details.resource_1_name, organizer_details.resource_1_link],
                      [organizer_details.resource_2_name, organizer_details.resource_2_link],
                      [organizer_details.resource_3_name, organizer_details.resource_3_link],
                      [organizer_details.resource_4_name, organizer_details.resource_4_link]]
    lobby_left_logo = organizer_details.lobby_left_logo
    lobby_right_logo = organizer_details.lobby_right_logo
    lobby_video_link = organizer_details.lobby_video_link
    lobby_background_url = organizer_details.lobby_background_url
    lobby_banner_link = organizer_details.lobby_banner_link
    back_button = '/arena/homepage/' + company_name + '/' + stall_text + '/'
    back_button = urllib.parse.quote(back_button)

    event_stall_users = EventStallUsers.objects.filter(organizer_name=organizer_details)
    user_ids = [i.event_user_id for i in event_stall_users]

    users = MyUser.objects.filter(id__in=user_ids).order_by('name')

    ### need to remove ####
    stalls = Stalls.objects.filter(organization=organizer_details)
    stall_texts = [i.unique_url for i in stalls]
    lobby_banner_images_left = [organizer_details.lobby_banner_image1, organizer_details.lobby_banner_image2,
                                organizer_details.lobby_banner_image3, organizer_details.lobby_banner_image4]
    lobby_banner_images_right = [organizer_details.lobby_banner_image5, organizer_details.lobby_banner_image6,
                                 organizer_details.lobby_banner_image7, organizer_details.lobby_banner_image8]

    notifications_array,users_array = get_chats(requests,organizer_details)
    users_chat = zip(notifications_array, users_array)

    context = {
        'hall_titles': hall_titles,
        'banner_links': resource_links,
        'lobby_left_logo': lobby_left_logo,
        'lobby_right_logo': lobby_right_logo,
        'lobby_video_link': lobby_video_link,
        'lobby_background_type': organizer_details.lobby_background_type,
        'lobby_background_url': lobby_background_url,
        'company_name': company_name,
        'stall_text': stall_text,
        'lobby_banner_link': lobby_banner_link,
        'registered_users': calculate_registered_users(organizer_details),
        'stall_texts': stall_texts,
        'back_button': back_button,
        'hall_array': hall_array(organizer_details),
        'lobby_banner_images_left': lobby_banner_images_left,
        'lobby_banner_images_right': lobby_banner_images_right,
        'users':users,
        'users_chat':users_chat,
        'current_user': MyUser.objects.get(id=requests.user.id),
    }

    # return render(requests, 'main_website/lobby_page.html', context)
    return render(requests, 'new/lobby_page.html', context)


# @user_authorized_for_page
def auditorium(requests, company_name, stall_text):
    organizer_details = OrganizerDetails.objects.get(name=company_name)
    auditorium_background_image = organizer_details.auditorium_background_image
    polls = poll.objects.all()
    current_user_status = False
    poll_result = []
    if len(polls) == 0:
        pass
    else:
        poll_result = [polls[0].option_one_count, polls[0].option_two_count, polls[0].option_three_count, polls[0].option_four_count ]
        poll_answers = another_poll_answers.objects.all()
        print("Poll Answers are  ",poll_answers)
        question_id = polls[0].question_id
        for i in poll_answers:
            if i.user_id == requests.user.id and i.question_id == question_id:
                current_user_status = True
                break
    
    if organizer_details.auditorium_video_type == 'youtube':
        
        auditorium_youtube_name = organizer_details.auditorium_youtube_name
        auditorium_keynote_track = organizer_details.auditorium_keynote_track
        back_button = '/arena/lobby/' + company_name + '/' + stall_text + '/'
        back_button = urllib.parse.quote(back_button)

        notifications_array,users_array = get_chats(requests,organizer_details)
        users_chat = zip(notifications_array, users_array)
        context = {
            'auditorium_background_image': auditorium_background_image,
            'auditorium_keynote_track': auditorium_keynote_track,
            'auditorium_youtube_name': auditorium_youtube_name,
            'company_name': company_name,
            'stall_text': stall_text,
            'registered_users': calculate_registered_users(organizer_details),
            'back_button': back_button,
            'hall_array': hall_array(organizer_details),
            'users_chat':users_chat,
            'current_user': MyUser.objects.get(id=requests.user.id),    
            'polls' : polls,  
            'poll_status':current_user_status,
            'poll_result':poll_result
        }
        print("this is auditorium ")
        # return render(requests, 'main_website/auditorium.html', context)
        return render(requests, 'new/auditorium.html', context)
    else:
        zoom_id = organizer_details.zoom_meeting_id
        zoom_password = organizer_details.zoom_password

        back_button = '/arena/lobby/' + company_name + '/' + stall_text + '/'
        back_button = urllib.parse.quote(back_button)

        context = {
            'auditorium_background_image': auditorium_background_image,        
            'company_name': company_name,
            'stall_text': stall_text,
            'registered_users': calculate_registered_users(organizer_details),
            'zoom_meeting_id': zoom_id,
            'zoom_meeting_password': zoom_password,
            'back_button': back_button,
            'hall_array': hall_array(organizer_details),
            'polls' : polls,

main_website/templates/main_website/base.html
{% load static %}
<html>

	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		    <script src="https://cdnjs.cloudflare.com/ajax/libs/reconnecting-websocket/1.0.0/reconnecting-websocket.min.js"></script>
		    <!-- import #zmmtg-root css -->
		    <link type="text/css" rel="stylesheet" href="https://source.zoom.us/1.7.9/css/bootstrap.css" />
		    <link type="text/css" rel="stylesheet" href="https://source.zoom.us/1.7.9/css/react-select.css" />
		    <script src="{% static 'main_website/dataanalytics_websocket.js' %}"></script>

		    
		<head>		
		<script src="https://code.jquery.com/jquery-2.1.3.min.js"></script>
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
		<style>
			#hall_1{
			    /* padding-top: 5px; */
			    top: 53%;
			    position: absolute;
			    left: 21%;
			    text-align: center;
			}
			#hall_2{
			    top: 82.4%;
			    position: absolute;
			    left: 46.7%;
			    text-align: center;
			}
			#hall_3{
			    top: 62.2%;
			    position: absolute;
			    left: 45.7%;
			    text-align: center;
			}
			#hall_4{
			    top: 53%;
			    position: absolute;
			    left: 73%;
			    text-align: center;
			}
			.hall{
				position: absolute;
/*			    border: beige;
			    border-style: solid;
			    padding: 15px;*/
			}
			.hall:hover{
				/*background-color: lightyello;*/
				background: rgba(76, 175, 80, 0.1);;
			}
			.label{
				font-size: 1.5em;
				font-weight: bold;
				font-family: initial;
				color: black;

			}
			b{
				font-size: 13px !important;
				color:red;

			}
			#box{
			    position: absolute;
			    left: 36%;
			    top: 5%;
			    border-style: double;
				border-color: black;
				margin: 2px;

			}
			#box_auditorium{
				position: absolute;
			    left: 38%;
			    top: 20%;
			    border-style: double;
				border-color: black;
				margin: 2px;
			}
			.gradient-border {
			  --borderWidth: 3px;
			  background: #1D1F20;
			  position: relative;
			  border-radius: var(--borderWidth);
			}
			.gradient-border:after {
			  content: '';
			  position: absolute;
			  top: calc(-1 * var(--borderWidth));
			  left: calc(-1 * var(--borderWidth));
			  height: calc(100% + var(--borderWidth) * 2);
			  width: calc(100% + var(--borderWidth) * 2);
			  background: linear-gradient(60deg, #f79533, #f37055, #ef4e7b, #a166ab, #5073b8, #1098ad, #07b39b, #6fba82);
			  border-radius: calc(2 * var(--borderWidth));
			  z-index: -1;
			  animation: animatedgradient 3s ease alternate infinite;
			  background-size: 300% 300%;
			}

			.small_image{
				z-index: 0;
				position:absolute;
				margin: 2px;
				top: 25%;
				border-style: double;
			    border-width: 5px;
			    border-color: black;
			}
			.left_lobby_image{
				left: 20%;
							}
			.right_lobby_image{
				left:66%;
			}
			.banner_image{
				left: 63.5%;
			    position: absolute;
			    top: 70%;
			}

			.resource_link{
				display:block;
				margin: 10px;
				margin-left: 20px;
				margin-right: 20px;
				z-index: 100;
			}


		.modal-dialog{
		    position: relative;
		    display: table; /* This is important */ 
		    overflow-y: auto;    
		    overflow-x: auto;
		    width: auto;
		    min-width: 300px;   
		}

		.navbar{
			margin-bottom: 0px !important;
		}
		.row{
			margin-left: 0px !important;
			margin-right: 0px !important;
		}

		.modal-dialog {
		  height: 90%; /* = 90% of the .modal-backdrop block = %90 of the screen */
		}
		.modal-content {
		  height: 100%; /* = 100% of the .modal-dialog block */
		}
		.navigation_header{
			font-size: 15px;
		}
		.center_navigation_header{
			font-size: 20px;
		    color: white;
		}
		.stall_video{
			top: 5%;
			position: absolute;
			right: 5.2%;
		}

	    @media (orientation:portrait){
	        #wrapper { display:none; }
	        #warning-message { display:block; }
	    }
	    @media (orientation: landscape) {
	        #warning-message { display:none; }
	    }		

	    .temp_box{
/*			border-color: black;
			border-style: double;
			border-width: 5px;*/
			width: 14%; 
			height: 11%;
			position: absolute;

	    }

		.video-container{
			position: absolute;
		}
		.lobby_video_container{
/*			top: 17%;
			left: 38.5%;
			height: 22.2%;
			width: 20.5%;*/
		    top: 28%;
		    left: 43.7%;
		    height: 11.3%;
		    width: 10.5%;			
		}		

		.lobby_video_container_auditorium{
			top: 15%;
			left: 29%;
			height: 33.7%;
			width: 42.5%;
		}		

		.video-container iframe {
			position: absolute;
			top: 0;
			left: 0;
			width: 100%;
			height: 100%;
		}

		.label_enter{
			animation: blinkingBackground 2s infinite;
			color: white;
		}

		b{
			color: white;
		}

		@keyframes blinkingBackground{
				0%		{ background-color: #10c018;}
				25%		{ background-color: #1056c0;}
				50%		{ background-color: #ef0a1a;}
				75%		{ background-color: #254878;}
				100%	{ background-color: #04a1d5;}
		}


		.stall_text{
			font-size: 10px;
			font-weight: bold;
			animation: blinkingText 2s infinite;

		}

		@keyframes blinkingText{
				0%		{ color: #000000;}
				25%		{ color: #1056c0;}
				50%		{ color: #ef0a1a;}
				/*75%		{ color: #254878;}*/
				/*100%	{ color: #04a1d5;}*/
		}		


		.stall_video_container{
			top: 38%;
    		left: 52.5%;
			height: 22.2%;
			width: 20.5%;			
		}
		.temp_lobby_banner{
			display: block;
			text-align: center;
			color: white;
		}
		.temp_banner{
			color: white;
			background-color: black;
			opacity: 0.8; 
			border-radius:5px;
			padding:5px;
		}

		</style>
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>		
	</head>
	<body>
		<div id='wrapper'>
			<nav class="navbar navbar-expand-md navbar-dark bg-dark navigation_header">
			    <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
			        <ul class="navbar-nav mr-auto">
<!-- 			            <li class="nav-item ">
			                <a class="nav-link" href="{% url 'main_website:auditorium' company_name=company_name stall_text=stall_text %}">Auditorium</a>
			            </li> -->
			            <li class="nav-item">
			                <a class="nav-link" href={{ back_button }}>Back</a>
			            </li>

			            <!-- <li class="nav-item">
			                <a class="nav-link" href="{% url 'main_website:first_floor' company_name=company_name stall_text=stall_text %}">First floor</a>
			            </li> -->
			            {% if hall_array.2 %}		            
				            <li class="nav-item ">
				                <a class="nav-link" href="{% url 'main_website:exhibit_hall' company_name=company_name stall_text=stall_text %}">Exhibit Hall</a>
				            </li>
				        {% endif %}
			            {% if hall_array.0 %}		            
				            <li class="nav-item ">
				                <a class="nav-link" href="{% url 'main_website:lobby' company_name=company_name stall_text=stall_text %}">Lobby</a>
				            </li>
				        {% endif %}
			            {% if hall_array.3 %}		            				        
				            <li class="nav-item ">
				                <a class="nav-link" href="{% url 'main_website:social_lounge' company_name=company_name stall_text=stall_text %}">Social Lounge</a>
				            </li>			            			            
				        {% endif %}
			            {% if hall_array.1 %}		            				        
				            <li class="nav-item ">
				                <a class="nav-link" href="{% url 'main_website:info_desk' company_name=company_name stall_text=stall_text %}">Info Center</a>
				            </li>			            			     
				        {% endif %}       			            
			        </ul>
			    </div>
			    <div class="mx-auto order-0 center_navigation_header" style='width: 100%; font-size: 15px; text-align: center;'>
			    	{{ company_name }}
			        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".dual-collapse2">
			            <span class="navbar-toggler-icon"></span>
			        </button>
			    </div>
			    <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
			        <ul class="navbar-nav ml-auto" style='float:right;'>
			            <li class="nav-item">
			            	<a class="nav-link" href="#">Registered Users- {{ registered_users }}  </a>		            	
			            </li>
			            <li class="nav-item">
			                <a class="nav-link" href="{% url 'users:logout' company_name=company_name stall_text=stall_text %}">Logout</a>
			            </li>
			        </ul>
			    </div>
			</nav>
			<div class='row' style='position: relative; height:100%;'>
	        {% block content %}{% endblock %}
			</div>		
		</div>
		<div id='warning-message' style='background-color: black;'>
			<img src="https://www.robscanlon.com/pleaserotate/demo.gif" style='width:100%;height: 100%;'></img>
			<h1 style="font-size: 40px; color:white; position: absolute; top:0%; text-align: center;">Please rotate Mobile </h1>

		</div>

	</body>


</html>

main_website/templates/main_website/feedback_form.html
{% load static %}
{% load crispy_forms_tags %}
<html>
    <head>

    </head>
    <body>
        <h1>SUMMIT EVALUATION FORM</h1>
        <h3>India Food Nutrition Summit 2020</h3>
        <p>25th Sept 2020| please help us make this conference better next year by filling out this short questionnaire. </p>
        <br>
        <br>

<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>

    </body>
</html>

main_website/templates/main_website/stall_details_page.html
{% extends 'main_website/base.html' %}
{% load static %}
{% block content %}


	<img  src="{{ background.url }}" style="z-index: 0; width:100%; height:100%; " /> 
	<div class="video-container stall_video_container" id="image_stall">
		<iframe src="{{ stall_video_url }}" allowfullscreen autoplay picture-in-picture> </iframe>
	</div>
	<a href="{{ stall_doc_url.url }}" class = 'stall_text' style="z-index: 1; position: absolute; left: 76%;top: 40%; font-size:9px;" download="doc.pdf" onclick=stall_pdf()>Project</br> Details</a>
	<a href="{% url 'main_website:stalls' company_name=company_name stall_text=stall_text  %}" class = 'stall_text' style="z-index: 1; position: absolute; left: 75.5%;top: 49.5%; font-size: 10px;">लाइव वीडियो </br> चैट</a>
	<a href="{{ stall_web_link }}"  preload="auto" class = 'stall_text' style="z-index: 1; position: absolute; left: 76%;top: 59.8%; font-size:9px;" onclick=stall_website()>Website</a> 

{% endblock %}

main_website/templates/main_website/stall_owner.html
stall