main_website/urls.py
from django.urls import path
from . import views


app_name = 'main_website'

urlpatterns = [
    path('homepage/<str:company_name>/<str:stall_text>/', views.home_page, name='main_page'),
    path('lobby/<str:company_name>/<str:stall_text>/', views.lobby_page, name='lobby'),    
    path('auditorium/<str:company_name>/<str:stall_text>/', views.auditorium, name='auditorium'),     
    path('info_desk/<str:company_name>/<str:stall_text>/', views.info_desk, name='info_desk'),    
    path('exhibit_hall/<str:company_name>/<str:stall_text>/', views.exhibit_hall, name='exhibit_hall'),    
    path('resource_center/<str:company_name>/<str:stall_text>/', views.resource_center, name='resource_center'),    
    path('social_lounge/<str:company_name>/<str:stall_text>/', views.social_lounge, name='social_lounge'),                       
    path('zoom_start/', views.zoom_start, name='zoom_start'),    
    path('stall/<str:company_name>/<str:stall_text>/',views.stall,name='stalls'),                       
    path('stall_iframe',views.stall_iframe,name='stall_iframe'),
    path('stall_portal/<str:company_name>/<str:stall_text>/',views.stall_portal,name='stall_portal'),
    path('stall_details/<str:company_name>/<str:stall_text>/',views.stall_details,name='stall_details'),
    path('auditorium_owner/<str:company_name>/',views.auditorium_owner,name='auditorium_owner'),        
    path('stall_owner_page/<str:company_name>/',views.stall_owner_page,name='stall_owner_page'),
    path('stall_owner_chat/<str:company_name>/<str:stall_text>/',views.stall_owner_chat,name='stall_owner_chat'),    
    path('question',views.question,name = 'question'),
    path('photobooth/',views.photobooth,name='photobooth'),
    path('stall_analytics/<str:company_name>/<str:stall_text>/',views.stall_analytics,name='stall_analytics'),
    path('stall_add_documents/<str:company_name>/<str:stall_text>/',views.stall_add_documents,name='stall_add_documents'),
    path('stall_add_sales_representative/<str:company_name>/<str:stall_text>/',views.stall_add_sales_representatives,name='stall_add_sales_representatives'),


    path('first_floor/<str:company_name>/<str:stall_text>/',views.first_floor,name="first_floor"),
    path('first_floor/room1/<str:company_name>/<str:stall_text>/',views.first_floor_link1,name="first_floor_link1"),
    path('first_floor/room2/<str:company_name>/<str:stall_text>/',views.first_floor_link2,name="first_floor_link2"),
    path('first_floor/room3/<str:company_name>/<str:stall_text>/',views.first_floor_link3,name="first_floor_link3"),


    path('submit_polling_results/<str:company_name>/<str:stall_text>/',views.submit_polling_results,name="submit_polling_results"),
    path('update_doc/<str:company_name>/<str:stall_text>/',views.update_document,name="update_document"),
    path('update_social_media_link/<str:company_name>/<str:stall_text>/',views.update_social_media_link,name="update_social_media_link"),
    path('new_doc/<str:company_name>/<str:stall_text>/',views.new_document,name="new_document"),
    path('new_representative/<str:company_name>/<str:stall_text>/',views.new_representative,name="new_representative"),
    path('update_representative/<str:company_name>/<str:stall_text>/',views.update_representative,name="update_representative"),
    path('schedule_call/<str:company_name>/<str:stall_text>/',views.schedule_call_by_user,name="schedule_call"),

    path('feedback',views.FeeBack.as_view(),name='feedback')
]

users/urls.py
from django.urls import path,reverse_lazy
from django.contrib.auth import views as auth_views
from . import views

app_name = 'users'

urlpatterns = [
	path('',views.basic_login_redirect,name='basic_login'),
    path('register/<str:company_name>/<str:stall_text>/',views.register,name = 'register'),
    path('login/<str:company_name>/<str:stall_text>/', views.CustomLoginView.as_view(), name='login'),
    path('logout/<str:company_name>/<str:stall_text>/', views.CustomLogoutView.as_view(), name='logout'),
]

webinarwall/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('dashboard/', include('dashboard.urls')),    
    path('arena/', include('main_website.urls')),       
    # path('main_website/',include()) 
] #+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_website/forms.py
from django import forms
from users.models import MyUser
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import gettext, gettext_lazy as _
from django.contrib.auth import authenticate
from dashboard.models import OrganizerDetails
from main_website.models import FeedBack
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, ButtonHolder, Submit, Field
from crispy_forms.layout import Layout, Submit, Row, Column


class FeedbackForm(forms.ModelForm):

    class Meta:
        model = FeedBack
        fields = '__all__'
        labels = {
            "question1": "Please rate your overall satisfaction with the virtual conference",
            "question2": "Please rate your overall satisfaction with the exhibits area",
            "question3": "Please rate your overall satisfaction with the format of the conference",
            "question4": "Please rate your overall satisfaction with the access and convenience with the Platform use",
            "question5": "Please rate your overall satisfaction with the access and convenience with the Platform used ",
            "question6": "Please rate Quality of Audio & Visuals ",
            "question7": "The Quality of our sponsors / partners for the summit",
            "question8": "Have your organization embarking on any strategic initiatives approved to improve on Technology / IOT etc.?",
            "question9": "The likely time period of undertaking these strategic initiatives is",
            "question10": "Please provide any comments you have on future conference  platforms,  topics, speakers or general suggestions regarding the conference",
        }

    def __init__(self, *args, **kwargs):
        super(FeedbackForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
                Row('question1'),
                Row('question2'),
                'question3',
                'question4',
                'question5',
                'question6',
                'question7',
                'question8',
                'question9',
                'question10',
            ButtonHolder(
                Submit('submit', 'Submit', css_class='button white')
            )
        )

main_website/views.py
from django.shortcuts import render
from dashboard.models import OrganizerDetails, EventStallUsers, Stalls, StallZoom, Stall_Owner_documents,Stall_Sales_Representatives
from users.decorators import user_authorized_for_page
from django.urls import reverse_lazy
import hashlib
import hmac
import base64
import time
from django.contrib import messages
from django.http import JsonResponse, HttpResponse, HttpResponseRedirect
from users.models import MyUser
from .models import Notification, Analytics, Permanent_Poll_Answers
import urllib.parse
# from django.http import JsonResponse
from .models import Question, poll, another_poll_answers
import pdb
from .models import Message
from users.models import MyUser
from django.db.models import Q
from django.urls import reverse
from django.http import HttpResponseRedirect
from main_website.forms import FeedbackForm
from django.views.generic import CreateView
# Create your views here.

def calculate_registered_users(organizer):
    # organizer = OrganizerDetails.objects.get(name = company_name)
    return EventStallUsers.objects.filter(organizer_name=organizer).count()


def hall_array(organizer_details):
    return [organizer_details.hall_title_1, organizer_details.hall_title_2, organizer_details.hall_title_3,
            organizer_details.hall_title_4]


def question(request):
    question = request.GET.get('question', None)
    Question.objects.create(question=question, user=MyUser.objects.get(id=request.user.id).name)
    return JsonResponse({'success': 'success'})


#@user_authorized_for_page
def home_page(requests, company_name, stall_text):
    organizer_details = OrganizerDetails.objects.get(name=company_name)
    background_type = organizer_details.main_page_background_type
    background_url = organizer_details.main_page_background_url
    lobby_page_url = '127.0.0.1:8000/lobby/' + company_name + stall_text

    event_stall_users = EventStallUsers.objects.filter(organizer_name=organizer_details)
    user_ids = [i.event_user_id for i in event_stall_users]

    users = MyUser.objects.filter(id__in=user_ids).order_by('name')

    resource_links = [[organizer_details.resource_1_name, organizer_details.resource_1_link],
                      [organizer_details.resource_2_name, organizer_details.resource_2_link],
                      [organizer_details.resource_3_name, organizer_details.resource_3_link],
                      [organizer_details.resource_4_name, organizer_details.resource_4_link]]

    slides = [organizer_details.main_page_ppt_image1, organizer_details.main_page_ppt_image2,
              organizer_details.main_page_ppt_image3, organizer_details.main_page_ppt_image4]
    notifications_array,users_array = get_chats(requests,organizer_details)
    users_chat = zip(notifications_array, users_array)

    context = {
        'background_type': background_type,
        'banner_links': resource_links,
        'background_url': background_url,
        'lobby_page_url': lobby_page_url,
        'company_name': company_name,
        'stall_text': stall_text,
        'registered_users': calculate_registered_users(organizer_details),
        'main_page_front_banner_image': organizer_details.main_page_front_banner_image,
        
        'main_page_back_banner_image1': organizer_details.main_page_back_banner_image1,
        'main_page_back_banner_image2': organizer_details.main_page_back_banner_image2,
        'main_page_back_banner_image3': organizer_details.main_page_back_banner_image3,
        'main_page_back_banner_image4': organizer_details.main_page_back_banner_image4,
        
        'slides': slides,
        'hall_array': hall_array(organizer_details),
        'users':users,
        'users_chat':users_chat,
        'current_user': MyUser.objects.get(id=requests.user.id),        
    }

    # return render(requests, 'main_website/main_page.html', context)
    return render(requests, 'new/main_page.html', context)


# @user_authorized_for_page
def lobby_page(requests, company_name, stall_text):
    organizer_details = OrganizerDetails.objects.get(name=company_name)
    hall_titles = [organizer_details.hall_title_1, organizer_details.hall_title_2, organizer_details.hall_title_3,
                   organizer_details.hall_title_4]
    resource_links = [[organizer_details.resource_1_name, organizer_details.resource_1_link],
                      [organizer_details.resource_2_name, organizer_details.resource_2_link],
                      [organizer_details.resource_3_name, organizer_details.resource_3_link],
                      [organizer_details.resource_4_name, organizer_details.resource_4_link]]
    lobby_left_logo = organizer_details.lobby_left_logo
    lobby_right_logo = organizer_details.lobby_right_logo
    lobby_video_link = organizer_details.lobby_video_link
    lobby_background_url = organizer_details.lobby_background_url
    lobby_banner_link = organizer_details.lobby_banner_link
    back_button = '/arena/homepage/' + company_name + '/' + stall_text + '/'
    back_button = urllib.parse.quote(back_button)

    event_stall_users = EventStallUsers.objects.filter(organizer_name=organizer_details)
    user_ids = [i.event_user_id for i in event_stall_users]

    users = MyUser.objects.filter(id__in=user_ids).order_by('name')

    ### need to remove ####
    stalls = Stalls.objects.filter(organization=organizer_details)
    stall_texts = [i.unique_url for i in stalls]
    lobby_banner_images_left = [organizer_details.lobby_banner_image1, organizer_details.lobby_banner_image2,
                                organizer_details.lobby_banner_image3, organizer_details.lobby_banner_image4]
    lobby_banner_images_right = [organizer_details.lobby_banner_image5, organizer_details.lobby_banner_image6,
                                 organizer_details.lobby_banner_image7, organizer_details.lobby_banner_image8]

    notifications_array,users_array = get_chats(requests,organizer_details)
    users_chat = zip(notifications_array, users_array)

    context = {
        'hall_titles': hall_titles,
        'banner_links': resource_links,
        'lobby_left_logo': lobby_left_logo,
        'lobby_right_logo': lobby_right_logo,
        'lobby_video_link': lobby_video_link,
        'lobby_background_type': organizer_details.lobby_background_type,
        'lobby_background_url': lobby_background_url,
        'company_name': company_name,
        'stall_text': stall_text,
        'lobby_banner_link': lobby_banner_link,
        'registered_users': calculate_registered_users(organizer_details),
        'stall_texts': stall_texts,
        'back_button': back_button,
        'hall_array': hall_array(organizer_details),
        'lobby_banner_images_left': lobby_banner_images_left,
        'lobby_banner_images_right': lobby_banner_images_right,
        'users':users,
        'users_chat':users_chat,
        'current_user': MyUser.objects.get(id=requests.user.id),
    }

    # return render(requests, 'main_website/lobby_page.html', context)
    return render(requests, 'new/lobby_page.html', context)


# @user_authorized_for_page
def auditorium(requests, company_name, stall_text):
    organizer_details = OrganizerDetails.objects.get(name=company_name)
    auditorium_background_image = organizer_details.auditorium_background_image
    polls = poll.objects.all()
    current_user_status = False
    poll_result = []
    if len(polls) == 0:
        pass
    else:
        poll_result = [polls[0].option_one_count, polls[0].option_two_count, polls[0].option_three_count, polls[0].option_four_count ]
        poll_answers = another_poll_answers.objects.all()
        print("Poll Answers are  ",poll_answers)
        question_id = polls[0].question_id
        for i in poll_answers:
            if i.user_id == requests.user.id and i.question_id == question_id:
                current_user_status = True
                break
    
    if organizer_details.auditorium_video_type == 'youtube':
        
        auditorium_youtube_name = organizer_details.auditorium_youtube_name
        auditorium_keynote_track = organizer_details.auditorium_keynote_track
        back_button = '/arena/lobby/' + company_name + '/' + stall_text + '/'
        back_button = urllib.parse.quote(back_button)

        notifications_array,users_array = get_chats(requests,organizer_details)
        users_chat = zip(notifications_array, users_array)
        context = {
            'auditorium_background_image': auditorium_background_image,
            'auditorium_keynote_track': auditorium_keynote_track,
            'auditorium_youtube_name': auditorium_youtube_name,
            'company_name': company_name,
            'stall_text': stall_text,
            'registered_users': calculate_registered_users(organizer_details),
            'back_button': back_button,
            'hall_array': hall_array(organizer_details),
            'users_chat':users_chat,
            'current_user': MyUser.objects.get(id=requests.user.id),    
            'polls' : polls,  
            'poll_status':current_user_status,
            'poll_result':poll_result
        }
        print("this is auditorium ")
        # return render(requests, 'main_website/auditorium.html', context)
        return render(requests, 'new/auditorium.html', context)
    else:
        zoom_id = organizer_details.zoom_meeting_id
        zoom_password = organizer_details.zoom_password

        back_button = '/arena/lobby/' + company_name + '/' + stall_text + '/'
        back_button = urllib.parse.quote(back_button)

        context = {
            'auditorium_background_image': auditorium_background_image,        
            'company_name': company_name,
            'stall_text': stall_text,
            'registered_users': calculate_registered_users(organizer_details),
            'zoom_meeting_id': zoom_id,
            'zoom_meeting_password': zoom_password,
            'back_button': back_button,
            'hall_array': hall_array(organizer_details),
            'polls' : polls,

main_website/templates/new/first_floor/first_floor_link1.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
	<link rel="stylesheet" href="{% static 'new/page3/style.css' %}">
	<link rel="stylesheet" href="{% static 'new/page3/navbar.css' %}">
	<script src="https://kit.fontawesome.com/73b6dfc8d5.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.0.0/animate.min.css"/>
	  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
	  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <script src="{% static 'main_website/dataanalytics_websocket.js' %}"></script>
    <audio id="myAudio">
      <source src="https://webinarzappastatic.s3.ap-south-1.amazonaws.com/media/WhatsApp+Audio+2020-09-06+at+3.02.16+PM.mpeg" type="audio/mpeg">
      Your browser does not support the audio element.
    </audio>
    <script src="{% static 'main_website/dataanalytics_websocket.js' %}"></script>

    <link rel="stylesheet" href="{% static 'main_website/chat_box.css' %}" />

    <style>
       @media (orientation:portrait){
	        #wrapper { display:none; }
	        #warning-message { display:block; }
	    }
	    @media (orientation: landscape) {
	        #warning-message { display:none; }
	    }
	    .btn2{
            top: 17.2%;
            left: 26.5%;
            width: 44%;
            position: absolute;
	    }
	    button{
	        background-color: blue;
	    }
	    p{
            color: white;
            font-weight: bold;
            font-size: 20px;
	    }
    </style>

</head>
<body>


    <div class="page_custom" style="background-image: url(https://webinarzappastatic.s3.ap-south-1.amazonaws.com/media/THEATER.jpg)">
        <iframe allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen
                class="vdo wow animate__fadeIn" data-wow-delay="1.5s"
                frameborder="0" src="https://www.youtube.com/embed/MJHVmZGNl2Y"></iframe>

        <button class="default-btn btn2" ><a onclick="myFunction()" href="https://agilent.webex.com/agilent/j.php?MTID=mb19117891e9ad9a160e6536023d015c7" style="text-decoration: none;"><p class="animate__slideInUp wow"data-wow-duration="2s">Click to Here to Join Meeting</p></a></button>

        <!-- THis is polling modal -->
        <div class="modal fade" id="pollingModal" role="dialog">
            <div class="modal-dialog" style="display:table; max-width: 100%; width: 80%; max-height: 100%; height:80%;">
                <div class="modal-content">
                    <div class="modal-header">
                        <span>Polling Question</span>
                        <button class="close" data-dismiss="modal" type="button">&times;</button>
                    </div>
                    <br>
                    {% for poll in polls %}
                    <form method="POST" action="{% url 'main_website:submit_polling_results' company_name=company_name stall_text=stall_text  %}">
                    {% csrf_token %}

                        <label style="margin-left: 15px" value={{poll.question_id}} name="question_id">{{poll.question}}</label><br><br>

                        <input style="margin-left: 15px" type="radio" name="options" value="{{poll.option_one}}">&nbsp;{{poll.option_one}}
                        <input style="margin-left: 15px" type="radio" name="options" value="{{poll.option_two}}">&nbsp;{{poll.option_two}}
                        <input style="margin-left: 15px" type="radio" name="options" value="{{poll.option_three}}">&nbsp;{{poll.option_three}}
                        <input style="margin-left: 15px" type="radio" name="options" value="{{poll.option_four}}">&nbsp;{{poll.option_four}}
                        <input type="hidden" value="{{poll.question_id}}" name="question_id">
                    <div class="modal-footer">
                        <input type="submit" class="btn btn-default" type="button">
                        <button class="btn btn-default" data-dismiss="modal" type="button">Close</button>
                    </div>
                    </form>
                    {% endfor %}
                </div>

            </div>
        </div>
        <div class="modal fade" id="pollingResults">
            <div class="modal-dialog modal-dialog-centered">
              <div class="modal-content">

                <!-- Modal Header -->
                <div class="modal-header">
                  <h4 class="modal-title">Pooling Results</h4>
                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>

                <!-- Modal body -->
                <div class="modal-body">
                    {% for poll in polls %}
                    <label style="margin-left: 15px" value={{poll.question_id}} name="question_id">{{poll.question}}</label><br><br>
                    <div style="margin-left: 20px;">
                    <ul>
                        &nbsp;&nbsp;&nbsp;&nbsp;   <li>Votes for {{poll.option_one}}&nbsp;&nbsp;&nbsp;&nbsp;{{poll_result.0}}</li>
                        &nbsp;&nbsp;&nbsp;&nbsp;<li>Votes for {{poll.option_two}}&nbsp;&nbsp;&nbsp;&nbsp;{{poll_result.1}}</li>
                        &nbsp;&nbsp;&nbsp;&nbsp;<li>Votes for {{poll.option_three}}&nbsp;&nbsp;&nbsp;&nbsp;{{poll_result.2}}</li>
                        &nbsp;&nbsp;&nbsp;&nbsp;<li>Votes for {{poll.option_four}}&nbsp;&nbsp;&nbsp;&nbsp;{{poll_result.3}}</li>
                    </ul>
                    </div>
                    {% endfor %}
                </div>

                <!-- Modal footer -->
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>

              </div>
            </div>
          </div>
<div class="modal fade" id="myModal" role="dialog">
            <div class="modal-dialog" style="display:table; max-width: 100%; width: 80%; max-height: 100%; height:80%;">
                <div class="modal-content">
                    <div class="modal-header">
                        <button class="close" data-dismiss="modal" type="button">&times;</button>
                    </div>
                    <iframe allowfullscreen autoplay picture-in-picture src="{{ auditorium_keynote_track }}"
                            style='width:100%; height:700px;'></iframe>
                    <div class="modal-footer">
                        <button class="btn btn-default" data-dismiss="modal" type="button">Close</button>
                    </div>
                </div>

            </div>
        </div>

        <div class="modal fade" id="chatModal2" role="dialog">
            <div class="modal-dialog" style="display:table; max-width: 100%; width: 80%; max-height: 50%; height:50%;">
                <div class="modal-content">
                    <div class="modal-header">
                        Ask a Question
                        <button class="close" data-dismiss="modal" type="button">&times;</button>
                    </div>

                    <div class="modal-footer" id="sendmessage2">
                        <input id="chat-message-input2" style='width:100%; height: 100%;' type="text"/>
                        <button class="btn btn-default" id='send2' type="button">Send</button>
                    </div>
                </div>
            </div>
        </div>

  <div class="navbar_custom">
    <ul><li><a href={{ back_button }}><i class="fas fa-arrow-left"></i></li><li>Back</a></li></ul>
    <ul><li><a href="{% url 'main_website:first_floor' company_name=company_name stall_text=stall_text %}"><i class="far fa-building"></i></li><li>First Floor</a></li></ul>

    <ul><li><a href="{% url 'main_website:lobby' company_name=company_name stall_text=stall_text %}"><i class="fas fa-home"></i></li><li>Lobby</a></li></ul>
    {% if hall_array.0 %}
        <ul><li><a href="{% url 'main_website:auditorium' company_name=company_name stall_text=stall_text %}"><i class="fa fa-building" aria-hidden="true"></i></li><li>{{ hall_array.0 }}</a></li></ul>
    {% endif %}
    {% if hall_array.1 %}
        <ul><li><a href="{% url 'main_website:info_desk' company_name=company_name stall_text=stall_text %}"><i class="fas fa-info"></i></li><li>{{ hall_array.1 }}</a></li></ul>
    {% endif %}
    {% if hall_array.2 %}
        <ul><li><a href="{% url 'main_website:exhibit_hall' company_name=company_name stall_text=stall_text %}"><i class="fa fa-university" aria-hidden="true"></i></li><li>{{ hall_array.2 }}</a></li></ul>
    {% endif %}
    {% if hall_array.3 %}
        <ul><li><a href="{% url 'main_website:social_lounge' company_name=company_name stall_text=stall_text %}"><i class="fas fa-network-wired"></i></li><li>{{ hall_array.3 }}</a></li></ul>
    {% endif %}

    {% if hall_array.4 %}
        <ul><li><a href="{% url 'main_website:partners_tab' company_name=company_name stall_text=stall_text %}"><i class="fas fa-network-wired"></i></li><li>{{ hall_array.4 }}</a></li></ul>
    {% endif %}

    <ul><div id = "attendee_popup"><li>{{ registered_users }}</li><li>Attendees</div></li></ul>

    <ul><li><a href="{% url 'users:logout' company_name=company_name stall_text=stall_text %}"><i class="fas fa-sign-out-alt"></i></li><li>Log out</a></li></ul>
 </div>



 <div id='warning-message' style='background-color: black;'>
    <img src="https://www.robscanlon.com/pleaserotate/demo.gif" style='width:100%;height: 100%;'></img>
    <h1 style="font-size: 40px; color:white; position: absolute; top:0%; text-align: center;">Please rotate
        Mobile </h1>
</div>
		<iframe class="vdo wow animate__fadeIn" data-wow-delay="1.5s" src="{{ auditorium_youtube_name }}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/wow/1.1.2/wow.min.js"></script>
        <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>

      <script>
            new WOW().init();
      </script>
    <script>
                // You can change the speed and amount of cards here
var cardAmount = 4;
var flipSpeed = 4500;

// Preload all images to prevent blank cards
// because they're switched with CSS classes
(function preload(imageArray) {
    $(imageArray).each(function(){
        $('<img/>')[0].src = this;
    });
})(['https://source.unsplash.com/YQ3FpeQkNhA/800x600',
	'https://source.unsplash.com/gGC63oug3iY/800x600',
	'https://source.unsplash.com/PAcI-vmFL2g/800x600',
	'https://source.unsplash.com/_d0zgyMmYT8/800x600']);

// 3D flip slideshow
(function bfCards(elements, speed) {
	var cards = $('.cards');
	var container = cards.children('.cards__container');
	var front = container.children('.cards__front');
	var back = container.children('.cards__back');

	function swapArticleClass(element, newClass) {
		element.removeClass(function(index, css) {
			return (css.match(/(^|\s)card-\S+/g) || []).join(' ');
		});

		element.addClass(newClass);
	}

	var onTick = function(i) {
		setTimeout(function() {
			var nextClass;
			var currentClass = 'card-' + i;

			if (currentClass === elements)  {
				nextClass = 'card-' + (i + 1);
			} else {
				nextClass = 'card-1';
			}

			if (i % 2 === 0) {
				cards.addClass('is-flipped');
				swapArticleClass(back, currentClass);
				setTimeout(function() {
					swapArticleClass(front, nextClass);
				}, speed / 2);
			} else {
				cards.removeClass('is-flipped');
				swapArticleClass(front, currentClass);
				setTimeout(function() {
					swapArticleClass(back, nextClass);
				}, speed / 2);
			}
		}, speed * i);
	};

	function cycle() {
		for (var i = 1; i <= elements; i++) {
			onTick(i);
		}
	};

	cycle();
	setInterval(cycle, speed * elements);
})(cardAmount, flipSpeed);
            </script>

{% include 'new/everypage_chat.html' %}
{% comment %} {% include 'nav.html' %} {% endcomment %}
<script>
    window.addEventListener('click', function(e){
      if (document.getElementById('chatbox').contains(e.target)){
        // Clicked in box
      }
      else if(document.getElementById('attendee_popup').contains(e.target)){
        document.getElementById('chatbox').style.display = "block";
        $('#attendee_popup').css('color','black');
      }
      else{
        document.getElementById('chatbox').style.display = "none";
      }
    });

    $('#attendee_popup').click(function(){
        document.getElementById('chatbox').style.display = "block";
    })
</script>

<script>
    new WOW().init();
</script>

    </div>
</body>
</html>