main_website/urls.py
from django.urls import path
from . import views


app_name = 'main_website'

urlpatterns = [
    path('homepage/<str:company_name>/<str:stall_text>/', views.home_page, name='main_page'),
    path('lobby/<str:company_name>/<str:stall_text>/', views.lobby_page, name='lobby'),    
    path('auditorium/<str:company_name>/<str:stall_text>/', views.auditorium, name='auditorium'),     
    path('info_desk/<str:company_name>/<str:stall_text>/', views.info_desk, name='info_desk'),    
    path('exhibit_hall/<str:company_name>/<str:stall_text>/', views.exhibit_hall, name='exhibit_hall'),    
    path('resource_center/<str:company_name>/<str:stall_text>/', views.resource_center, name='resource_center'),    
    path('social_lounge/<str:company_name>/<str:stall_text>/', views.social_lounge, name='social_lounge'),                       
    path('zoom_start/', views.zoom_start, name='zoom_start'),    
    path('stall/<str:company_name>/<str:stall_text>/',views.stall,name='stalls'),                       
    path('stall_iframe',views.stall_iframe,name='stall_iframe'),
    path('stall_portal/<str:company_name>/<str:stall_text>/',views.stall_portal,name='stall_portal'),
    path('stall_details/<str:company_name>/<str:stall_text>/',views.stall_details,name='stall_details'),
    path('auditorium_owner/<str:company_name>/',views.auditorium_owner,name='auditorium_owner'),        
    path('stall_owner_page/<str:company_name>/',views.stall_owner_page,name='stall_owner_page'),
    path('stall_owner_chat/<str:company_name>/<str:stall_text>/',views.stall_owner_chat,name='stall_owner_chat'),    
    path('question',views.question,name = 'question'),
    path('photobooth/',views.photobooth,name='photobooth'),
    path('stall_analytics/<str:company_name>/<str:stall_text>/',views.stall_analytics,name='stall_analytics'),
    path('stall_add_documents/<str:company_name>/<str:stall_text>/',views.stall_add_documents,name='stall_add_documents'),
    path('stall_add_sales_representative/<str:company_name>/<str:stall_text>/',views.stall_add_sales_representatives,name='stall_add_sales_representatives'),


    path('first_floor/<str:company_name>/<str:stall_text>/',views.first_floor,name="first_floor"),
    path('first_floor/room1/<str:company_name>/<str:stall_text>/',views.first_floor_link1,name="first_floor_link1"),
    path('first_floor/room2/<str:company_name>/<str:stall_text>/',views.first_floor_link2,name="first_floor_link2"),
    path('first_floor/room3/<str:company_name>/<str:stall_text>/',views.first_floor_link3,name="first_floor_link3"),


    path('submit_polling_results/<str:company_name>/<str:stall_text>/',views.submit_polling_results,name="submit_polling_results"),
    path('update_doc/<str:company_name>/<str:stall_text>/',views.update_document,name="update_document"),
    path('update_social_media_link/<str:company_name>/<str:stall_text>/',views.update_social_media_link,name="update_social_media_link"),
    path('new_doc/<str:company_name>/<str:stall_text>/',views.new_document,name="new_document"),
    path('new_representative/<str:company_name>/<str:stall_text>/',views.new_representative,name="new_representative"),
    path('update_representative/<str:company_name>/<str:stall_text>/',views.update_representative,name="update_representative"),
    path('schedule_call/<str:company_name>/<str:stall_text>/',views.schedule_call_by_user,name="schedule_call"),

    path('feedback',views.FeeBack.as_view(),name='feedback')
]

users/urls.py
from django.urls import path,reverse_lazy
from django.contrib.auth import views as auth_views
from . import views

app_name = 'users'

urlpatterns = [
	path('',views.basic_login_redirect,name='basic_login'),
    path('register/<str:company_name>/<str:stall_text>/',views.register,name = 'register'),
    path('login/<str:company_name>/<str:stall_text>/', views.CustomLoginView.as_view(), name='login'),
    path('logout/<str:company_name>/<str:stall_text>/', views.CustomLogoutView.as_view(), name='logout'),
]

webinarwall/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('dashboard/', include('dashboard.urls')),    
    path('arena/', include('main_website.urls')),       
    # path('main_website/',include()) 
] #+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_website/forms.py
from django import forms
from users.models import MyUser
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import gettext, gettext_lazy as _
from django.contrib.auth import authenticate
from dashboard.models import OrganizerDetails
from main_website.models import FeedBack
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, ButtonHolder, Submit, Field
from crispy_forms.layout import Layout, Submit, Row, Column


class FeedbackForm(forms.ModelForm):

    class Meta:
        model = FeedBack
        fields = '__all__'
        labels = {
            "question1": "Please rate your overall satisfaction with the virtual conference",
            "question2": "Please rate your overall satisfaction with the exhibits area",
            "question3": "Please rate your overall satisfaction with the format of the conference",
            "question4": "Please rate your overall satisfaction with the access and convenience with the Platform use",
            "question5": "Please rate your overall satisfaction with the access and convenience with the Platform used ",
            "question6": "Please rate Quality of Audio & Visuals ",
            "question7": "The Quality of our sponsors / partners for the summit",
            "question8": "Have your organization embarking on any strategic initiatives approved to improve on Technology / IOT etc.?",
            "question9": "The likely time period of undertaking these strategic initiatives is",
            "question10": "Please provide any comments you have on future conference  platforms,  topics, speakers or general suggestions regarding the conference",
        }

    def __init__(self, *args, **kwargs):
        super(FeedbackForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
                Row('question1'),
                Row('question2'),
                'question3',
                'question4',
                'question5',
                'question6',
                'question7',
                'question8',
                'question9',
                'question10',
            ButtonHolder(
                Submit('submit', 'Submit', css_class='button white')
            )
        )

main_website/views.py
from django.shortcuts import render
from dashboard.models import OrganizerDetails, EventStallUsers, Stalls, StallZoom, Stall_Owner_documents,Stall_Sales_Representatives
from users.decorators import user_authorized_for_page
from django.urls import reverse_lazy
import hashlib
import hmac
import base64
import time
from django.contrib import messages
from django.http import JsonResponse, HttpResponse, HttpResponseRedirect
from users.models import MyUser
from .models import Notification, Analytics, Permanent_Poll_Answers
import urllib.parse
# from django.http import JsonResponse
from .models import Question, poll, another_poll_answers
import pdb
from .models import Message
from users.models import MyUser
from django.db.models import Q
from django.urls import reverse
from django.http import HttpResponseRedirect
from main_website.forms import FeedbackForm
from django.views.generic import CreateView
# Create your views here.

def calculate_registered_users(organizer):
    # organizer = OrganizerDetails.objects.get(name = company_name)
    return EventStallUsers.objects.filter(organizer_name=organizer).count()


def hall_array(organizer_details):
    return [organizer_details.hall_title_1, organizer_details.hall_title_2, organizer_details.hall_title_3,
            organizer_details.hall_title_4]


def question(request):
    question = request.GET.get('question', None)
    Question.objects.create(question=question, user=MyUser.objects.get(id=request.user.id).name)
    return JsonResponse({'success': 'success'})


#@user_authorized_for_page
def home_page(requests, company_name, stall_text):
    organizer_details = OrganizerDetails.objects.get(name=company_name)
    background_type = organizer_details.main_page_background_type
    background_url = organizer_details.main_page_background_url
    lobby_page_url = '127.0.0.1:8000/lobby/' + company_name + stall_text

    event_stall_users = EventStallUsers.objects.filter(organizer_name=organizer_details)
    user_ids = [i.event_user_id for i in event_stall_users]

    users = MyUser.objects.filter(id__in=user_ids).order_by('name')

    resource_links = [[organizer_details.resource_1_name, organizer_details.resource_1_link],
                      [organizer_details.resource_2_name, organizer_details.resource_2_link],
                      [organizer_details.resource_3_name, organizer_details.resource_3_link],
                      [organizer_details.resource_4_name, organizer_details.resource_4_link]]

    slides = [organizer_details.main_page_ppt_image1, organizer_details.main_page_ppt_image2,
              organizer_details.main_page_ppt_image3, organizer_details.main_page_ppt_image4]
    notifications_array,users_array = get_chats(requests,organizer_details)
    users_chat = zip(notifications_array, users_array)

    context = {
        'background_type': background_type,
        'banner_links': resource_links,
        'background_url': background_url,
        'lobby_page_url': lobby_page_url,
        'company_name': company_name,
        'stall_text': stall_text,
        'registered_users': calculate_registered_users(organizer_details),
        'main_page_front_banner_image': organizer_details.main_page_front_banner_image,
        
        'main_page_back_banner_image1': organizer_details.main_page_back_banner_image1,
        'main_page_back_banner_image2': organizer_details.main_page_back_banner_image2,
        'main_page_back_banner_image3': organizer_details.main_page_back_banner_image3,
        'main_page_back_banner_image4': organizer_details.main_page_back_banner_image4,
        
        'slides': slides,
        'hall_array': hall_array(organizer_details),
        'users':users,
        'users_chat':users_chat,
        'current_user': MyUser.objects.get(id=requests.user.id),        
    }

    # return render(requests, 'main_website/main_page.html', context)
    return render(requests, 'new/main_page.html', context)


# @user_authorized_for_page
def lobby_page(requests, company_name, stall_text):
    organizer_details = OrganizerDetails.objects.get(name=company_name)
    hall_titles = [organizer_details.hall_title_1, organizer_details.hall_title_2, organizer_details.hall_title_3,
                   organizer_details.hall_title_4]
    resource_links = [[organizer_details.resource_1_name, organizer_details.resource_1_link],
                      [organizer_details.resource_2_name, organizer_details.resource_2_link],
                      [organizer_details.resource_3_name, organizer_details.resource_3_link],
                      [organizer_details.resource_4_name, organizer_details.resource_4_link]]
    lobby_left_logo = organizer_details.lobby_left_logo
    lobby_right_logo = organizer_details.lobby_right_logo
    lobby_video_link = organizer_details.lobby_video_link
    lobby_background_url = organizer_details.lobby_background_url
    lobby_banner_link = organizer_details.lobby_banner_link
    back_button = '/arena/homepage/' + company_name + '/' + stall_text + '/'
    back_button = urllib.parse.quote(back_button)

    event_stall_users = EventStallUsers.objects.filter(organizer_name=organizer_details)
    user_ids = [i.event_user_id for i in event_stall_users]

    users = MyUser.objects.filter(id__in=user_ids).order_by('name')

    ### need to remove ####
    stalls = Stalls.objects.filter(organization=organizer_details)
    stall_texts = [i.unique_url for i in stalls]
    lobby_banner_images_left = [organizer_details.lobby_banner_image1, organizer_details.lobby_banner_image2,
                                organizer_details.lobby_banner_image3, organizer_details.lobby_banner_image4]
    lobby_banner_images_right = [organizer_details.lobby_banner_image5, organizer_details.lobby_banner_image6,
                                 organizer_details.lobby_banner_image7, organizer_details.lobby_banner_image8]

    notifications_array,users_array = get_chats(requests,organizer_details)
    users_chat = zip(notifications_array, users_array)

    context = {
        'hall_titles': hall_titles,
        'banner_links': resource_links,
        'lobby_left_logo': lobby_left_logo,
        'lobby_right_logo': lobby_right_logo,
        'lobby_video_link': lobby_video_link,
        'lobby_background_type': organizer_details.lobby_background_type,
        'lobby_background_url': lobby_background_url,
        'company_name': company_name,
        'stall_text': stall_text,
        'lobby_banner_link': lobby_banner_link,
        'registered_users': calculate_registered_users(organizer_details),
        'stall_texts': stall_texts,
        'back_button': back_button,
        'hall_array': hall_array(organizer_details),
        'lobby_banner_images_left': lobby_banner_images_left,
        'lobby_banner_images_right': lobby_banner_images_right,
        'users':users,
        'users_chat':users_chat,
        'current_user': MyUser.objects.get(id=requests.user.id),
    }

    # return render(requests, 'main_website/lobby_page.html', context)
    return render(requests, 'new/lobby_page.html', context)


# @user_authorized_for_page
def auditorium(requests, company_name, stall_text):
    organizer_details = OrganizerDetails.objects.get(name=company_name)
    auditorium_background_image = organizer_details.auditorium_background_image
    polls = poll.objects.all()
    current_user_status = False
    poll_result = []
    if len(polls) == 0:
        pass
    else:
        poll_result = [polls[0].option_one_count, polls[0].option_two_count, polls[0].option_three_count, polls[0].option_four_count ]
        poll_answers = another_poll_answers.objects.all()
        print("Poll Answers are  ",poll_answers)
        question_id = polls[0].question_id
        for i in poll_answers:
            if i.user_id == requests.user.id and i.question_id == question_id:
                current_user_status = True
                break
    
    if organizer_details.auditorium_video_type == 'youtube':
        
        auditorium_youtube_name = organizer_details.auditorium_youtube_name
        auditorium_keynote_track = organizer_details.auditorium_keynote_track
        back_button = '/arena/lobby/' + company_name + '/' + stall_text + '/'
        back_button = urllib.parse.quote(back_button)

        notifications_array,users_array = get_chats(requests,organizer_details)
        users_chat = zip(notifications_array, users_array)
        context = {
            'auditorium_background_image': auditorium_background_image,
            'auditorium_keynote_track': auditorium_keynote_track,
            'auditorium_youtube_name': auditorium_youtube_name,
            'company_name': company_name,
            'stall_text': stall_text,
            'registered_users': calculate_registered_users(organizer_details),
            'back_button': back_button,
            'hall_array': hall_array(organizer_details),
            'users_chat':users_chat,
            'current_user': MyUser.objects.get(id=requests.user.id),    
            'polls' : polls,  
            'poll_status':current_user_status,
            'poll_result':poll_result
        }
        print("this is auditorium ")
        # return render(requests, 'main_website/auditorium.html', context)
        return render(requests, 'new/auditorium.html', context)
    else:
        zoom_id = organizer_details.zoom_meeting_id
        zoom_password = organizer_details.zoom_password

        back_button = '/arena/lobby/' + company_name + '/' + stall_text + '/'
        back_button = urllib.parse.quote(back_button)

        context = {
            'auditorium_background_image': auditorium_background_image,        
            'company_name': company_name,
            'stall_text': stall_text,
            'registered_users': calculate_registered_users(organizer_details),
            'zoom_meeting_id': zoom_id,
            'zoom_meeting_password': zoom_password,
            'back_button': back_button,
            'hall_array': hall_array(organizer_details),
            'polls' : polls,

main_website/templates/new/exhibit_hall.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/reconnecting-websocket/1.0.0/reconnecting-websocket.min.js"></script>
    <link href="{% static 'new/page6/style.css' %}" rel="stylesheet">
    <script crossorigin="anonymous" src="https://kit.fontawesome.com/73b6dfc8d5.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.0.0/animate.min.css" rel="stylesheet"/>
    <link href="{% static 'new/page6/navbar.css' %}" rel="stylesheet">
    <script src="{% static 'main_website/dataanalytics_websocket.js' %}"></script>
    <link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" rel="stylesheet">
    <audio id="myAudio">
      <source src="https://webinarzappastatic.s3.ap-south-1.amazonaws.com/media/WhatsApp+Audio+2020-09-06+at+3.02.16+PM.mpeg" type="audio/mpeg">
      Your browser does not support the audio element.
    </audio>          
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-migrate-3.0.0.min.js"></script>
    <script crossorigin="anonymous"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script crossorigin="anonymous"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'main_website/chat_box.css' %}" />            
    <title></title>
    <style>
       @media (orientation:portrait){
	        #wrapper { display:none; }
	        #warning-message { display:block; }
	    }
	    @media (orientation: landscape) {
	        #warning-message { display:none; }
	    }
    </style>
</head>
<body>
<img src = {{ background_image.url }} style="width: 100%; height: 100%; position: absolute;"/>
<!--style="background: url({{ background_image.url }}); background-repeat: no-repeat;&ndash;&gt;-->
<!--    background-size: contain;">-->
<style>
    .stall_image{
        width: 17%;
        height: 17%;
        position: absolute;
    }
    .stall_image_bottom{
        width: 20%;
        height: 26%;
        position: absolute;
    }
    .stall_image1{
        top: 27%;
        left: 5%;
    }
    .stall_image2{
        top: 27%;
        left: 27%;
    }
    .stall_image3{
        top: 27%;
        left: 50%;
    }
    .stall_image4{
        top: 27%;
        left: 74%;
        width: 21% !important;
    }
    .stall_image5{
        top: 53%;
        left: 0%;
    }
    .stall_image6{
        top: 54%;
        left: 26%;
    }
    .stall_image7{
        top: 54%;
        left: 51%;
    }
    .stall_image8{
        top: 54%;
        left: 81%;
        width: 19%;
    }

</style>
<div id='wrapper'>
        <a href="{% url 'main_website:stall_details' company_name=company_name stall_text=text.0  %}" class="stall_image stall_image1"></a>
        <a href="{% url 'main_website:stall_details' company_name=company_name stall_text=text.1  %}" class="stall_image stall_image2"></a>
        <a href="{% url 'main_website:stall_details' company_name=company_name stall_text=text.2  %}" class="stall_image stall_image3"></a>
        <a href="{% url 'main_website:stall_details' company_name=company_name stall_text=text.3  %}" class="stall_image stall_image4"></a>
        <a href="{% url 'main_website:stall_details' company_name=company_name stall_text=text.4  %}" class="stall_image_bottom stall_image5"></a>
        <a href="{% url 'main_website:stall_details' company_name=company_name stall_text=text.5  %}" class="stall_image_bottom stall_image6"></a>
        <a href="{% url 'main_website:stall_details' company_name=company_name stall_text=text.6  %}" class="stall_image_bottom stall_image7"></a>
        <a href="{% url 'main_website:stall_details' company_name=company_name stall_text=text.7  %}" class="stall_image_bottom stall_image8"></a>
    <div class="page">
        <!-- <img src="{{ background_image.url }}" class="bg" alt=""> -->


        {% include 'new/everypage_chat.html' %}
        {% include 'nav.html' %}
        <script src="https://cdnjs.cloudflare.com/ajax/libs/wow/1.1.2/wow.min.js"></script>
        <script>
        new WOW().init();
        </script>
    </div>
</div>


<script>
    window.addEventListener('click', function(e){   
      if (document.getElementById('chatbox').contains(e.target)){
        // Clicked in box
      }
      else if(document.getElementById('attendee_popup').contains(e.target)){
        document.getElementById('chatbox').style.display = "block";
      }
      else{
        document.getElementById('chatbox').style.display = "none";
      }
    });

    $('#attendee_popup').click(function(){
        document.getElementById('chatbox').style.display = "block";
    })
</script>


<div id='warning-message' style='background-color: black;'>
    <img src="https://www.robscanlon.com/pleaserotate/demo.gif" style='width:100%;height: 100%;'></img>
    <h1 style="font-size: 40px; color:white; position: absolute; top:0%; text-align: center;">Please rotate Mobile </h1>
</div>
</body>
</html>

main_website/templates/new/lobby_page.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="{% static 'new/page2/style.css' %}">
     <link rel="stylesheet" href="{% static 'new/page2/navbar.css' %}">
     <script src="https://cdnjs.cloudflare.com/ajax/libs/reconnecting-websocket/1.0.0/reconnecting-websocket.min.js"></script>
    <script src="https://kit.fontawesome.com/73b6dfc8d5.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.0.0/animate.min.css"/>
    <link rel="stylesheet" href="{% static 'main_website/chat_box.css' %}" />
    <script src="{% static 'main_website/dataanalytics_websocket.js' %}"></script> 
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script> 
    var vid = document.getElementById("myVideo"); 

    function myFunction() {
      var x = document.getElementById("myDIV");
      if (x.style.display === "none") {
        x.style.display = "block";
        vid.play();
    
    vid.onended = function(e){
      window.location.replace("{% url 'main_website:auditorium' company_name=company_name stall_text=stall_text %}")
    }
  }// else {
    //x.style.display = "none";
  //}
}

</script> 

    <script src="https://code.jquery.com/jquery-migrate-3.0.0.min.js"></script>  
    <title>{{ company_name }}</title>
        <style>
       @media (orientation:portrait){
	        #wrapper { display:none; }
	        #warning-message { display:block; }
	    }
	    @media (orientation: landscape) {
	        #warning-message { display:none; }
	    }
.video-container {
  position: absolute;
  top: 0;
  bottom: 0;
  width: 100%;
  height: 100%;
  overflow: hidden;
}
.video-container video {
  /* Make video to at least 100% wide and tall */
  min-width: 100%;
  min-height: 100%;

  /* Setting width & height to auto prevents the browser from stretching or squishing the video */
  width: auto;
  height: auto;

  /* Center the video */
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%,-50%);
}
.btn2{
    left: 22.2%;
    }

    </style>
        <audio id="myAudio">
          <source src="https://webinarzappastatic.s3.ap-south-1.amazonaws.com/media/WhatsApp+Audio+2020-09-06+at+3.02.16+PM.mpeg" type="audio/mpeg">
          Your browser does not support the audio element.
        </audio>

</head>
<body>
<div class="video-container video-container-right" style="z-index:-20;">
  <video muted id="right_video">
    <source src="https://webinarzappastatic.s3.ap-south-1.amazonaws.com/media/Right+Teleportation.mp4" type="video/mp4" />
  </video>
</div>

<div class="video-container video-container-left"  style="z-index:-20;">
  <video muted id="left_video">
    <source src="https://webinarzappastatic.s3.ap-south-1.amazonaws.com/media/Left+Teleportation.mp4" type="video/mp4" />
  </video>
</div>


<div id='wrapper'>
    <iframe class="vdo" src="{{ lobby_video_link }}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>    
    <div class="page">
      <!-- added virtual video -->
      <div class="myDIV">
         <video src="https://audivideo.s3.ap-south-1.amazonaws.com/LEFT+VIDEO.mp4"  width="100%" height="100%" id="myVideo" style="display: none;"></video>
      </div>

    {% if lobby_background_type == 'video' %}
        <video autoplay="" class="bg" data-setup="{}" height="100%" loop="" muted="" preload="auto"
               src="{{ lobby_background_url.url }}" style="z-index: 0; position: absolute;" width="100%"></video>
    {% else %}
        <img src="{{ lobby_background_url.url }}" class="bg" alt="">
    {% endif %}

        {% if hall_titles.1 %}
        <button class="default-btn btn1"><a href="{% url 'main_website:info_desk' company_name=company_name stall_text=stall_text %}" style="text-decoration: none;"><p class="animate__slideInUp wow"data-wow-duration="2s">{{ hall_titles.1 }}</p></a></button>
        {% endif %}
        {% if hall_titles.0 %}
        <button class="default-btn btn2" id="btn2"><p class="animate__slideInUp wow"data-wow-duration="2s">{{ hall_titles.0 }}</p></button>
        {% endif %}


<!--         <button class=""><a  href="{% url 'main_website:photobooth' %}" style="text-decoration: none;"><p class="animate__slideInUp wow"data-wow-duration="2s">photobooth</p></a></button> -->
         
        {% if hall_titles.2 %}
            <button class="default-btn btn3"><a href="{% url 'main_website:exhibit_hall' company_name=company_name stall_text=stall_text %}" style="text-decoration: none;"><p class="animate__slideInUp wow"data-wow-duration="2s">{{ hall_titles.2 }}</p></a></button>
        {% endif %}
        {% if hall_titles.3 %}
            <button class="default-btn btn4" id="btn4"><p class="animate__slideInUp wow"data-wow-duration="2s">{{ hall_titles.3 }}</p></button>
        {% endif %}


    </div>
    <div class="wrapper1">
        <div class="boxarea">
	   {% for image in lobby_banner_images_left %}
            <div class="slide{{ forloop.counter }} slide">
    	       <img src="{{ image.url }}" alt="">
            </div>
	   {% endfor %}
         </div>
    </div>
    <div class="wrapper2">
        <div class="boxarea">
           {% for image in lobby_banner_images_right %}
                <div class="slide{{ forloop.counter }} slide">
                   <img src="{{ image.url }}" alt="">
                </div>
           {% endfor %}
        </div>
    </div>
    {% include 'new/everypage_chat.html' %}

 {% include 'nav.html' %}
</div>
<div id='warning-message' style='background-color: black;'>
    <img src="https://www.robscanlon.com/pleaserotate/demo.gif" style='width:100%;height: 100%;'></img>
    <h1 style="font-size: 40px; color:white; position: absolute; top:0%; text-align: center;">Please rotate Mobile </h1>
</div>
<script>
    window.addEventListener('click', function(e){   
      if (document.getElementById('chatbox').contains(e.target)){
        // Clicked in box
      }
      else if(document.getElementById('attendee_popup').contains(e.target)){
        document.getElementById('chatbox').style.display = "block";
        $('#attendee_popup').css('color','black');
      }
      else{
        document.getElementById('chatbox').style.display = "none";
      }
    });

    $('#attendee_popup').click(function(){
        document.getElementById('chatbox').style.display = "block";        
        $('#attendee_popup').css('color','black');
    })
    $('#btn4').click(function(){
        $('.video-container-right').css('z-index',0);
        $('#right_video').get(0).play();
        $('#right_video').css('z-index',3000);
        $('#wrapper').css('display','none');

    })

    $('#btn2').click(function(){
        $('.video-container-left').css('z-index',0);
        $('#left_video').get(0).play();
        $('#wrapper').css('display','none');
        $('#left_video').css('z-index',3000);
    })

    document.getElementById('right_video').addEventListener('ended',myHandler,false);
    function myHandler(e) {
        window.location.replace("{% url 'main_website:social_lounge' company_name=company_name stall_text=stall_text %}");
    }
    document.getElementById('left_video').addEventListener('ended',myHandler2,false);
    function myHandler2(e) {
        window.location.replace("{% url 'main_website:auditorium' company_name=company_name stall_text=stall_text %}");
    }

</script>
    <script>
        new WOW().init();
        </script>

</body>
</html>